use ecommerce_db;
SHOW TABLES;

-- How many users are there on our platform
SELECT
	COUNT(user_id) AS total_user
FROM EVENTS;

-- How many total unique users signed up on our platform
SELECT
	COUNT(DISTINCT user_id) As total_user
FROM events;

-- letss see how does order table looks like
SELECT * FROM orders;

-- How many orders were placed in total, and what is our total revenue?
SELECT 
	COUNT(DISTINCT order_id) AS total_orders, -- total order placed
    ROUND(SUM(payment_value)) AS total_revenue -- total revenue
FROM payments;

-- Question: What is the average amount a customer spends on an order?
SELECT 
    ROUND(AVG(payment_value), 2) AS average_order_value
FROM payments;

-- Question: How many times did each action (like signup, view, purchase) happen in total?
SELECT 
    event_type, 
    COUNT(*) AS total_count
FROM events
GROUP BY event_type
ORDER BY total_count DESC;

-- Which marketing channel brought us the most users?
SELECT 
    acquisition_channel, 
    COUNT(DISTINCT user_id) AS total_users
FROM events
GROUP BY acquisition_channel
ORDER BY total_users DESC;

-- How many users were placed in the Control group versus the Treatment group?
SELECT 
    group_assignment, 
    COUNT(user_id) AS total_users
FROM ab_test_assignment
GROUP BY group_assignment;

-- What is the most popular payment method used by customers?
SELECT 
    payment_type, 
    COUNT(order_id) AS total_orders
FROM payments
GROUP BY payment_type
ORDER BY total_orders DESC;

-- kinda complex question

-- "What is the drop-off rate and average time elapsed (in hours) between activation and purchase for converted users?"
WITH user_timestamps AS (
    SELECT 
        user_id,
        MAX(CASE WHEN event_type = 'activated' THEN event_timestamp END) AS activation_time,
        MAX(CASE WHEN event_type = 'purchased' THEN event_timestamp END) AS purchase_time
    FROM events
    GROUP BY user_id
)
SELECT 
    COUNT(activation_time) AS total_activated_users,
    COUNT(purchase_time) AS total_purchased_users,
    ROUND((1 - (COUNT(purchase_time) * 1.0 / COUNT(activation_time))) * 100, 2) AS drop_off_percentage,
    ROUND(AVG(TIMESTAMPDIFF(HOUR, activation_time, purchase_time)), 2) AS avg_hours_to_purchase
FROM user_timestamps
WHERE activation_time IS NOT NULL;

-- "Which acquisition channel drives the highest overall conversion rate from signup to purchase?"
SELECT 
    acquisition_channel,
    COUNT(DISTINCT user_id) AS total_signups,
    COUNT(DISTINCT CASE WHEN event_type = 'purchased' THEN user_id END) AS total_buyers,
    ROUND(
        (COUNT(DISTINCT CASE WHEN event_type = 'purchased' THEN user_id END) * 100.0) 
        / COUNT(DISTINCT user_id), 
        2
    ) AS conversion_rate_pct
FROM events
GROUP BY acquisition_channel
ORDER BY conversion_rate_pct DESC;

-- "What is the Average Order Value (AOV) and total revenue generated by each acquisition channel?"
SELECT 
    e.acquisition_channel,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(p.payment_value), 2) AS total_revenue,
    ROUND(SUM(p.payment_value) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM events e
JOIN orders o 
    ON e.user_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
WHERE e.event_type = 'signup'
GROUP BY e.acquisition_channel
ORDER BY total_revenue DESC;

-- "What percentage of purchasing customers placed more than one order?"
WITH customer_order_counts AS (
    SELECT 
        customer_id,
        COUNT(order_id) AS total_orders
    FROM orders
    GROUP BY customer_id
)
SELECT 
    COUNT(customer_id) AS total_buyers,
    SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) AS repeat_buyers,
    ROUND(
        (SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(customer_id), 
        2
    ) AS repeat_purchase_rate_pct
FROM customer_order_counts;

-- "How many unique users signed up each month, and how many of them completed a purchase in that same month?"
SELECT 
    DATE_FORMAT(e_signup.event_timestamp, '%Y-%m') AS cohort_month,
    COUNT(DISTINCT e_signup.user_id) AS total_signups,
    COUNT(DISTINCT e_purchase.user_id) AS same_month_buyers,
    ROUND(
        COUNT(DISTINCT e_purchase.user_id) * 100.0 / COUNT(DISTINCT e_signup.user_id), 
        2
    ) AS cohort_conversion_pct
FROM events e_signup
LEFT JOIN events e_purchase 
    ON e_signup.user_id = e_purchase.user_id 
    AND e_purchase.event_type = 'purchased'
    AND DATE_FORMAT(e_signup.event_timestamp, '%Y-%m') = DATE_FORMAT(e_purchase.event_timestamp, '%Y-%m')
WHERE e_signup.event_type = 'signup'
GROUP BY cohort_month
ORDER BY cohort_month ASC;